project:
  type: website
website:
  site-url: "https://github.com/shusenpu/capstone4ds.github.io/"
  sidebar:
    style: docked
    title: "Capstone Projects"
    logo: assets/logo.png
    tools:
      - icon: github
        href: https://github.com/shusenpu/capstone4ds.github.io
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Instructors
      - href: project.qmd
        text: Project Instructions
      # - section: "Units"
      #   contents:
      #     - units/unit1.qmd
      #     - units/unit2.ipynb
      #     - units/unit3.qmd
      - href: data.qmd
        text: Sample Projects
      #- href: license.qmd
      #  text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



