---
title: "IDC6940/MAT6903/MAT6910/STA6950 - Capstone Projects"
subtitle: "UWF - Mathematics and Statistics"
# listing:
#   - id: schedule
#     template: assets/schedule.ejs
#     contents: schedule.yml
#   - id: buttons
#     template: assets/buttons.ejs
#     contents: buttons.yml
---

```{=html}
<!--::: {#buttons}
:::



::: {.callout-note title="Welcome to Week 1 of Stat 999"}
:::

::: {.callout-note title="Welcome to Week 2"}
Things are picking up now.
:::-->
```
This course will provide you with an opportunity to apply the knowledge and skills that you have gained in the program. The capstone project will allow student to gain experience in mathematical modeling, data wrangling, data visualization, statistical modeling, machine learning, numerical simulation, reporting, and presenting the results. Upon the completion of this course, you will have a paper and slides to show to potential hiring managers.

## Schedule

\*Day indicates class meeting days of the week .

| **Week** | **Day**\* | **Topic(s)**                             | **Action**                                                               |
|:-----------:|:-----------:|-----------------------|:-----------------------|
|    1     |     1     | Intro to GitHub/RStudio/Quarto/Overleaf/Python/Matlab      | Introduction + Survey + Pick a Topic/Group                                         |
|          |     2     | Pick a Topic + Practice **(no meeting**) | Pick a Topic/Group                                                       |
|    2     |     1     | **Individual** research                  | Read and summarize research papers; Create **Individual** GitHub Website/Overleaf Document |
|          |     2     | **Individual** research (no meeting)     | Read and summarize research papers; Create **Individual** GitHub Website/Overleaf Document |
|    3     |     1     | **Individual** research                  | Read and summarize research papers; Add them to GitHub Website/Overleaf Document           |
|          |     2     | **Individual** research (no meeting)     | Read and summarize research papers; Add them to GitHub Website/Overleaf Document          |
|    4     |     1     | **Individual** research                  | Read and summarize research papers + polish writing on GitHub Website/Overleaf Document    |
|          |     2     | **Individual** research (no meeting)     | Read and summarize research papers + polish writing on GitHub Website/Overleaf Document    |
|    5     |     1     | **Team** research                        | finalize the group                                 |
|          |     2     | **Team** research (no meeting)           | write the project proposal                               |
|    6     |     1     | **Team** research                        | write the introduction/literature review + pick a problem to address              |
|          |     2     | **Team** research (no meeting)           | polish the introduction/literature review + pick a problem to address              |
|    7     |     1     | **Team** research                        | polish the introduction/literature review + write methodology                                       |
|          |     2     | **Team** research (no meeting)           | polish the introduction/literature review + write methodology                                       |
|    8     |     1     | **Team** research                        | polish intro+methods+write analysis                                                |
|          |     2     | **Team** research (no meeting)           | polish intro+methods+write analysis                                                 |
|    9     |     1     | **Team** research                        | Analysis/Computation/Simulation                                                 |
|          |     2     | **Team** research (no meeting)           | update the analysis and progress                                                 |
|    10    |     1     | **Team** research                        | analysis and results                                                     |
|          |     2     | **Team** research (no meeting)           | 1st draft due                                                     |
|    11    |     1     | **Team** research                        | analysis and results                                                     |
|          |     2     | **Team** research (no meeting)           | 2nd draft due                                                   |
|    12    |     1     | **Team** research                        | analysis and results                                                     |
|          |     2     | **Team** research (no meeting)           | Final draft + slides                                                   |
|    13    |     1     | **Team** research                        | mock presentation                                           |
|          |     2     | **Team** research (no meeting)           | polish report + slides                                           |
|    14    |     1     | **Team** research                        | Final Presentation                                                                |
|          |     2     | **Team** research (no meeting)           | Final Presentation                                                                         |
|    15    |     1     | Final paper + slides due                       |                                                             |
|          |     2     | Final paper + slides due                     |  final report + slides + code submission                                                            |
